/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silo;

/**
 *
 * @author Mystery-PC
 */
public class DeliveryNoteDetailPage extends javax.swing.JFrame {

    private DeliveryNoteCtl deliveryNoteCtl;
    
    /**
     * Creates new form DeliveryNoteDetailPage
     */
    public DeliveryNoteDetailPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendingForm = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();
        printDialog = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        barcodeCB = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        preparingBtn = new javax.swing.JButton();
        signBtn = new javax.swing.JButton();
        pendingBtn = new javax.swing.JButton();
        emailBtn = new javax.swing.JButton();
        printBtn = new javax.swing.JButton();

        sendingForm.setSize(new java.awt.Dimension(400, 250));

        jLabel2.setText("Email");

        emailTF.setPreferredSize(new java.awt.Dimension(200, 22));

        sendBtn.setText("Send");
        sendBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sendingFormLayout = new javax.swing.GroupLayout(sendingForm.getContentPane());
        sendingForm.getContentPane().setLayout(sendingFormLayout);
        sendingFormLayout.setHorizontalGroup(
            sendingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sendingFormLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(sendingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sendBtn)
                    .addGroup(sendingFormLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(85, 85, 85)
                        .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        sendingFormLayout.setVerticalGroup(
            sendingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendingFormLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(sendingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sendBtn)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        printDialog.setSize(new java.awt.Dimension(400, 300));

        jLabel3.setText("Select print options");

        okButton.setText("OK");
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
        });

        barcodeCB.setText("show barcode");

        javax.swing.GroupLayout printDialogLayout = new javax.swing.GroupLayout(printDialog.getContentPane());
        printDialog.getContentPane().setLayout(printDialogLayout);
        printDialogLayout.setHorizontalGroup(
            printDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printDialogLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(printDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barcodeCB)
                    .addComponent(jLabel3))
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton)
                .addGap(78, 78, 78))
        );
        printDialogLayout.setVerticalGroup(
            printDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printDialogLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barcodeCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jLabel1.setText("detail info");

        preparingBtn.setText("Preparing");
        preparingBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                preparingBtnMouseClicked(evt);
            }
        });

        signBtn.setText("Sign");
        signBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signBtnMouseClicked(evt);
            }
        });

        pendingBtn.setText("Pending");
        pendingBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendingBtnMouseClicked(evt);
            }
        });

        emailBtn.setText("Email");
        emailBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailBtnMouseClicked(evt);
            }
        });

        printBtn.setText("Print");
        printBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(signBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pendingBtn)
                        .addGap(70, 70, 70)
                        .addComponent(printBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailBtn))
                    .addComponent(preparingBtn)
                    .addComponent(jLabel1))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(preparingBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signBtn)
                    .addComponent(pendingBtn)
                    .addComponent(printBtn)
                    .addComponent(emailBtn))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preparingBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preparingBtnMouseClicked
        // TODO add your handling code here:
        deliveryNoteCtl.changeDeliveryNoteStatus("preparing");
    }//GEN-LAST:event_preparingBtnMouseClicked

    private void pendingBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingBtnMouseClicked
        // TODO add your handling code here:
        deliveryNoteCtl.changeDeliveryNoteStatus("pending");
    }//GEN-LAST:event_pendingBtnMouseClicked

    private void signBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signBtnMouseClicked
        // TODO add your handling code here:
        deliveryNoteCtl.changeDeliveryNoteStatus("completed");
    }//GEN-LAST:event_signBtnMouseClicked

    private void emailBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailBtnMouseClicked
        // TODO add your handling code here:
        sendingForm.setVisible(true);
    }//GEN-LAST:event_emailBtnMouseClicked

    private void sendBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendBtnMouseClicked
        // TODO add your handling code here:

//        tampilin alert

        sendSoftcopyDone();
    }//GEN-LAST:event_sendBtnMouseClicked

    private void printBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printBtnMouseClicked
        // TODO add your handling code here:
        printDialog.setVisible(true);
    }//GEN-LAST:event_printBtnMouseClicked

    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked
        // TODO add your handling code here:
        printDeliveryNote();
    }//GEN-LAST:event_okButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryNoteDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryNoteDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryNoteDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryNoteDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryNoteDetailPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox barcodeCB;
    private javax.swing.JButton emailBtn;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton okButton;
    private javax.swing.JButton pendingBtn;
    private javax.swing.JButton preparingBtn;
    private javax.swing.JButton printBtn;
    private javax.swing.JDialog printDialog;
    private javax.swing.JButton sendBtn;
    private javax.swing.JFrame sendingForm;
    private javax.swing.JButton signBtn;
    // End of variables declaration//GEN-END:variables

    void setCtl(DeliveryNoteCtl deliveryNoteCtl) {
        this.deliveryNoteCtl = deliveryNoteCtl;
    }

    private void sendSoftcopyDone() {
        sendingForm.setVisible(false);
        deliveryNoteCtl.sendSoftcopyDone();
    }

    private void printDeliveryNote() {
        printDialog.setVisible(false);
        deliveryNoteCtl.printDeliveryNote();
    }
}
