/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silo;

/**
 *
 * @author Mystery-PC
 */
public class DeliveryNoteDetailPage extends javax.swing.JFrame {

    private DeliveryNoteCtl deliveryNoteCtl;
    
    /**
     * Creates new form DeliveryNoteDetailPage
     */
    public DeliveryNoteDetailPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendingForm = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();
        printDialog = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        barcodeCB = new javax.swing.JCheckBox();
        preparingBtn = new javax.swing.JButton();
        signBtn = new javax.swing.JButton();
        pendingBtn = new javax.swing.JButton();
        emailBtn = new javax.swing.JButton();
        printBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        invoiceNumberLabel = new javax.swing.JLabel();
        deliveryNoteNumberLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        customerEmailAddressLabel = new javax.swing.JLabel();
        orderDateLabel = new javax.swing.JLabel();
        deliveryDateLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();

        sendingForm.setSize(new java.awt.Dimension(400, 250));

        jLabel2.setText("Email");

        emailTF.setPreferredSize(new java.awt.Dimension(200, 22));

        sendBtn.setText("Send");
        sendBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sendingFormLayout = new javax.swing.GroupLayout(sendingForm.getContentPane());
        sendingForm.getContentPane().setLayout(sendingFormLayout);
        sendingFormLayout.setHorizontalGroup(
            sendingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sendingFormLayout.createSequentialGroup()
                .addGroup(sendingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sendingFormLayout.createSequentialGroup()
                        .addContainerGap(37, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(85, 85, 85)
                        .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sendingFormLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendBtn)))
                .addGap(48, 48, 48))
        );
        sendingFormLayout.setVerticalGroup(
            sendingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendingFormLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(sendingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sendBtn)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        printDialog.setSize(new java.awt.Dimension(400, 300));

        jLabel3.setText("Select print options");

        okButton.setText("OK");
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
        });

        barcodeCB.setText("show barcode");

        javax.swing.GroupLayout printDialogLayout = new javax.swing.GroupLayout(printDialog.getContentPane());
        printDialog.getContentPane().setLayout(printDialogLayout);
        printDialogLayout.setHorizontalGroup(
            printDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printDialogLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(printDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barcodeCB)
                    .addComponent(jLabel3))
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton)
                .addGap(78, 78, 78))
        );
        printDialogLayout.setVerticalGroup(
            printDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printDialogLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barcodeCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        preparingBtn.setText("Preparing");
        preparingBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                preparingBtnMouseClicked(evt);
            }
        });

        signBtn.setText("Sign");
        signBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signBtnMouseClicked(evt);
            }
        });

        pendingBtn.setText("Pending");
        pendingBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendingBtnMouseClicked(evt);
            }
        });

        emailBtn.setText("Email");
        emailBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailBtnMouseClicked(evt);
            }
        });

        printBtn.setText("Print");
        printBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printBtnMouseClicked(evt);
            }
        });

        jLabel1.setText("invoice number");

        jLabel4.setText("delivery note number");

        jLabel5.setText("customer name");

        jLabel6.setText("customer email address");

        jLabel7.setText("order date");

        jLabel8.setText("delivery date");

        jLabel9.setText("status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(printBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailBtn)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(preparingBtn)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(signBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pendingBtn))))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deliveryNoteNumberLabel)
                    .addComponent(invoiceNumberLabel)
                    .addComponent(customerNameLabel)
                    .addComponent(customerEmailAddressLabel)
                    .addComponent(orderDateLabel)
                    .addComponent(deliveryDateLabel)
                    .addComponent(statusLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(invoiceNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(deliveryNoteNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(customerNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(customerEmailAddressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(orderDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(deliveryDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(statusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(preparingBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signBtn)
                    .addComponent(pendingBtn)
                    .addComponent(printBtn)
                    .addComponent(emailBtn))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preparingBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preparingBtnMouseClicked
        // TODO add your handling code here:
        deliveryNoteCtl.changeDeliveryNoteStatus("preparing", deliveryNoteNumberLabel.getText());
    }//GEN-LAST:event_preparingBtnMouseClicked

    private void pendingBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingBtnMouseClicked
        // TODO add your handling code here:
        deliveryNoteCtl.changeDeliveryNoteStatus("pending", deliveryNoteNumberLabel.getText());
    }//GEN-LAST:event_pendingBtnMouseClicked

    private void signBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signBtnMouseClicked
        // TODO add your handling code here:
        deliveryNoteCtl.changeDeliveryNoteStatus("completed", deliveryNoteNumberLabel.getText());
    }//GEN-LAST:event_signBtnMouseClicked

    private void emailBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailBtnMouseClicked
        // TODO add your handling code here:
        emailTF.setText("");
        
        sendingForm.setVisible(true);
    }//GEN-LAST:event_emailBtnMouseClicked

    private void sendBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendBtnMouseClicked
        // TODO add your handling code here:
        
//        tampilin alert
        Alert alert = new Alert("Delivery Note Sent !", 3);
        alert.setVisible(true);
        
        sendSoftcopyDone();
    }//GEN-LAST:event_sendBtnMouseClicked

    private void printBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printBtnMouseClicked
        // TODO add your handling code here:
        printDialog.setVisible(true);
    }//GEN-LAST:event_printBtnMouseClicked

    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked
        // TODO add your handling code here:
        printDeliveryNote();
    }//GEN-LAST:event_okButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox barcodeCB;
    private javax.swing.JLabel customerEmailAddressLabel;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JLabel deliveryDateLabel;
    private javax.swing.JLabel deliveryNoteNumberLabel;
    private javax.swing.JButton emailBtn;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel invoiceNumberLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel orderDateLabel;
    private javax.swing.JButton pendingBtn;
    private javax.swing.JButton preparingBtn;
    private javax.swing.JButton printBtn;
    private javax.swing.JDialog printDialog;
    private javax.swing.JButton sendBtn;
    private javax.swing.JFrame sendingForm;
    private javax.swing.JButton signBtn;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables

    void setCtl(DeliveryNoteCtl deliveryNoteCtl) {
        this.deliveryNoteCtl = deliveryNoteCtl;
    }

    private void sendSoftcopyDone() {
        sendingForm.setVisible(false);
        deliveryNoteCtl.sendSoftcopyDone();
    }

    private void printDeliveryNote() {
        printDialog.setVisible(false);
        deliveryNoteCtl.printDeliveryNote();
    }
    
    void prepareViewedDeliveryNote(DeliveryNote deliveryNote) {
        invoiceNumberLabel.setText(deliveryNote.getInvoiceNumber());
        deliveryNoteNumberLabel.setText(deliveryNote.getDeliveryNoteNumber());
        customerNameLabel.setText(deliveryNote.getCustomerName());
        customerEmailAddressLabel.setText(deliveryNote.getCustomerEmailAddress());
        orderDateLabel.setText(deliveryNote.getOrderDate());
        deliveryDateLabel.setText(deliveryNote.getDeliveryDate());
        statusLabel.setText(deliveryNote.getStatus());
    }

}
