/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silo;

import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mystery-PC
 */
public class MainPage extends javax.swing.JFrame {
    
    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        searchTF = new javax.swing.JTextField();
        searchItemBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        buttonHolder = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        searchTF2 = new javax.swing.JTextField();
        searchInvoiceBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        invoiceTable = new javax.swing.JTable();
        buttonHolder2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        searchTF3 = new javax.swing.JTextField();
        searchDeliveryNote = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        deliveryNoteTable = new javax.swing.JTable();
        buttonHolder3 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        itemMenu = new javax.swing.JMenu();
        deliveryNoteMenu = new javax.swing.JMenu();
        createDeliveryNoteMenu = new javax.swing.JMenu();
        invoiceMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SILo");

        addBtn.setText("Add");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });

        searchItemBtn.setText("Search");
        searchItemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchItemBtnMouseClicked(evt);
            }
        });

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Item ID", "Barcode", "Item Name", "Description", "Manufacturer", "URL", "Stock"
            }
        ));
        jScrollPane1.setViewportView(itemTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchItemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonHolder))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchItemBtn)
                    .addComponent(addBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(buttonHolder))
                .addContainerGap())
        );

        searchInvoiceBtn.setText("Search");
        searchInvoiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchInvoiceBtnMouseClicked(evt);
            }
        });

        invoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Invoice Number", "PO Number", "Supplier Name", "Order Date", "Delivery Date", "Status"
            }
        ));
        jScrollPane2.setViewportView(invoiceTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchInvoiceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonHolder2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchInvoiceBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(buttonHolder2))
                .addContainerGap())
        );

        searchDeliveryNote.setText("Search");
        searchDeliveryNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchDeliveryNoteMouseClicked(evt);
            }
        });

        deliveryNoteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Invoice Number", "Delivery Note Number", "Customer Name", "Customer Email Address", "Order Date", "Delivery Date", "Status"
            }
        ));
        jScrollPane3.setViewportView(deliveryNoteTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchDeliveryNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonHolder3))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDeliveryNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonHolder3, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        itemMenu.setText("Item");
        itemMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(itemMenu);

        deliveryNoteMenu.setText("Delivery Note");
        deliveryNoteMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliveryNoteMenuMouseClicked(evt);
            }
        });

        createDeliveryNoteMenu.setText("Create Delivery Note");
        createDeliveryNoteMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createDeliveryNoteMenuMouseClicked(evt);
            }
        });
        deliveryNoteMenu.add(createDeliveryNoteMenu);

        jMenuBar1.add(deliveryNoteMenu);

        invoiceMenu.setText("Invoice");
        invoiceMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoiceMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(invoiceMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemMenuMouseClicked
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        
        viewItemCtl.getListOfItem();
    }//GEN-LAST:event_itemMenuMouseClicked

    private void searchItemBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchItemBtnMouseClicked
        // TODO add your handling code here:
        viewItemCtl.searchItem(searchTF.getText());
    }//GEN-LAST:event_searchItemBtnMouseClicked

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        // TODO add your handling code here:
        itemCtl.requestNewItemForm();
    }//GEN-LAST:event_addBtnMouseClicked

    private void deliveryNoteMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryNoteMenuMouseClicked
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(true);
        
        viewDeliveryNoteCtl.getListOfDeliveryNote();
    }//GEN-LAST:event_deliveryNoteMenuMouseClicked

    private void invoiceMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceMenuMouseClicked
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
        jPanel3.setVisible(false);
        
        viewInvoiceCtl.getListOfInvoice();
    }//GEN-LAST:event_invoiceMenuMouseClicked

    private void searchInvoiceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchInvoiceBtnMouseClicked
        // TODO add your handling code here:
        viewInvoiceCtl.searchInvoice(searchTF2.getText());
    }//GEN-LAST:event_searchInvoiceBtnMouseClicked

    private void searchDeliveryNoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchDeliveryNoteMouseClicked
        // TODO add your handling code here:
        viewDeliveryNoteCtl.searchDeliveryNote(searchTF3.getText());
    }//GEN-LAST:event_searchDeliveryNoteMouseClicked

    private void createDeliveryNoteMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createDeliveryNoteMenuMouseClicked
        // TODO add your handling code here:
        deliveryNoteCtl.requestDeliveryNoteForm();
    }//GEN-LAST:event_createDeliveryNoteMenuMouseClicked

    private ViewItemCtl viewItemCtl;
    private ItemCtl itemCtl;
    private ViewDeliveryNoteCtl viewDeliveryNoteCtl;
    private DeliveryNoteCtl deliveryNoteCtl;
    private ViewInvoiceCtl viewInvoiceCtl;
    private InvoiceCtl invoiceCtl;
    
    private JButton[] editItemButton;
    private JButton[] viewInvoiceButton;
    private JButton[] viewDeliveryNoteButton;
    private int editedItemNo;
    private int viewedInvoiceNo;
    private int viewedDeliveryNoteNo;

    public int getEditedItemNo() {
        return editedItemNo;
    }

    public int getViewedInvoiceNo() {
        return viewedInvoiceNo;
    }

    public int getViewedDeliveryNoteNo() {
        return viewedDeliveryNoteNo;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JScrollPane buttonHolder;
    private javax.swing.JScrollPane buttonHolder2;
    private javax.swing.JScrollPane buttonHolder3;
    private javax.swing.JMenu createDeliveryNoteMenu;
    private javax.swing.JMenu deliveryNoteMenu;
    private javax.swing.JTable deliveryNoteTable;
    private javax.swing.JMenu invoiceMenu;
    private javax.swing.JTable invoiceTable;
    private javax.swing.JMenu itemMenu;
    private javax.swing.JTable itemTable;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton searchDeliveryNote;
    private javax.swing.JButton searchInvoiceBtn;
    private javax.swing.JButton searchItemBtn;
    private javax.swing.JTextField searchTF;
    private javax.swing.JTextField searchTF2;
    private javax.swing.JTextField searchTF3;
    // End of variables declaration//GEN-END:variables

        
    public void showListOfItem(Object[][] data) {
        showItem(data);
    }

    private void showItem(Object[][] data) {
        itemTable.setVisible(true);
        
//        add record item to table
        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        while(model.getRowCount() > 0)
        {
            model.removeRow(0);
        }
        buttonHolder.removeAll();
        
        editItemButton = new javax.swing.JButton[data.length];
        for(int i=0; i<data.length; i++){
            model.addRow(data[i]);
            
            editItemButton[i] = new javax.swing.JButton("Edit");
            editItemButton[i].setSize(80,16);
            editItemButton[i].setLocation(0, 20 + 16 * i);
            editItemButton[i].setName(data[i][0].toString());
            editItemButton[i].addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    editItemBtnClicked(evt);
                }
            });
            
            buttonHolder.add(editItemButton[i]);
        }
    }
    
    public void editItemBtnClicked(java.awt.event.MouseEvent evt) {
        javax.swing.JButton jButton = (javax.swing.JButton)evt.getSource();
        
        editedItemNo = viewItemCtl.findItemNo(jButton.getName());
        
        itemCtl.requestEditItemForm();
    }
    
    public void refreshListOfItem() {
        viewItemCtl.getListOfItem();
    }

    public void showListOfInvoice(Object[][] data) {
        showInvoice(data);
    }

    private void showInvoice(Object[][] data) {
        invoiceTable.setVisible(true);
        
//        add record invoice to table
        DefaultTableModel model = (DefaultTableModel) invoiceTable.getModel();
        while(model.getRowCount() > 0)
        {
            model.removeRow(0);
        }
        buttonHolder2.removeAll();
        
        viewInvoiceButton = new javax.swing.JButton[data.length];
        for(int i=0; i<data.length; i++){
            model.addRow(data[i]);
            
            viewInvoiceButton[i] = new javax.swing.JButton("View");
            viewInvoiceButton[i].setSize(80,16);
            viewInvoiceButton[i].setLocation(0, 20 + 16 * i);
            viewInvoiceButton[i].setName(data[i][0].toString());
            viewInvoiceButton[i].addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    viewInvoiceBtnClicked(evt);
                }
            });
            
            buttonHolder2.add(viewInvoiceButton[i]);
        }
    }
    
    public void viewInvoiceBtnClicked(java.awt.event.MouseEvent evt) {
        javax.swing.JButton jButton = (javax.swing.JButton)evt.getSource();
        
        viewedInvoiceNo = viewInvoiceCtl.findInvoiceNo(jButton.getName());
        
        invoiceCtl.getInvoiceDescription();
    }

    void refreshListOfInvoice() {
        viewInvoiceCtl.getListOfInvoice();
    }

    void setCtl(ViewItemCtl viewItemCtl, ItemCtl itemCtl, ViewDeliveryNoteCtl viewDeliveryNoteCtl, DeliveryNoteCtl deliveryNoteCtl, ViewInvoiceCtl viewInvoiceCtl, InvoiceCtl invoiceCtl) {
        this.viewItemCtl = viewItemCtl;
        this.itemCtl = itemCtl;
        this.viewDeliveryNoteCtl = viewDeliveryNoteCtl;
        this.deliveryNoteCtl = deliveryNoteCtl;
        this.viewInvoiceCtl = viewInvoiceCtl;
        this.invoiceCtl = invoiceCtl;
    }

    void showListOfDeliveryNote(Object[][] data) {
        showDeliveryNote(data);
    }

    private void showDeliveryNote(Object[][] data) {
        deliveryNoteTable.setVisible(true);
        
//        add record delivery note to table
        DefaultTableModel model = (DefaultTableModel) deliveryNoteTable.getModel();
        while(model.getRowCount() > 0)
        {
            model.removeRow(0);
        }
        buttonHolder3.removeAll();
        
        viewDeliveryNoteButton = new javax.swing.JButton[data.length];
        for(int i=0; i<data.length; i++){
            model.addRow(data[i]);
            
            viewDeliveryNoteButton[i] = new javax.swing.JButton("View");
            viewDeliveryNoteButton[i].setSize(80,16);
            viewDeliveryNoteButton[i].setLocation(0, 20 + 16 * i);
            viewDeliveryNoteButton[i].setName(data[i][1].toString());
            viewDeliveryNoteButton[i].addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    viewDeliveryNoteBtnClicked(evt);
                }
            });
            
            buttonHolder3.add(viewDeliveryNoteButton[i]);
        }
    }
    
    public void viewDeliveryNoteBtnClicked(java.awt.event.MouseEvent evt) {
        javax.swing.JButton jButton = (javax.swing.JButton)evt.getSource();
        
        viewedDeliveryNoteNo = viewDeliveryNoteCtl.findDeliveryNoteNo(jButton.getName());
        
        deliveryNoteCtl.getDeliveryNoteDescription();
    }
    
    void refreshListOfDeliveryNote() {
        viewDeliveryNoteCtl.getListOfDeliveryNote();
    }
}
